/*
 * recreationms_trading_tool
 * a simple trading tool to return the percentage drop of a coin using coingecko api for rates and historical data
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RecreationmsTradingTool) {
      root.RecreationmsTradingTool = {};
    }
    root.RecreationmsTradingTool.Data = factory(root.RecreationmsTradingTool.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Data model module.
   * @module model/Data
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Data</code>.
   * @alias module:model/Data
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Data} obj Optional instance to populate.
   * @return {module:model/Data} The populated <code>Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bitcoin'))
        obj.bitcoin = ApiClient.convertToType(data['bitcoin'], Object);
    }
    return obj;
  }

  /**
   * @member {Object} bitcoin
   */
  exports.prototype.bitcoin = undefined;


  return exports;

}));
