/*
 * recreationms_trading_tool
 * a simple trading tool to return the percentage drop of a coin using coingecko api for rates and historical data
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RecreationmsTradingTool) {
      root.RecreationmsTradingTool = {};
    }
    root.RecreationmsTradingTool.HistoricalData = factory(root.RecreationmsTradingTool.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The HistoricalData model module.
   * @module model/HistoricalData
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>HistoricalData</code>.
   * @alias module:model/HistoricalData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>HistoricalData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricalData} obj Optional instance to populate.
   * @return {module:model/HistoricalData} The populated <code>HistoricalData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('localization'))
        obj.localization = ApiClient.convertToType(data['localization'], Object);
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], Object);
      if (data.hasOwnProperty('market_data'))
        obj.marketData = ApiClient.convertToType(data['market_data'], Object);
      if (data.hasOwnProperty('community_data'))
        obj.communityData = ApiClient.convertToType(data['community_data'], Object);
      if (data.hasOwnProperty('developer_data'))
        obj.developerData = ApiClient.convertToType(data['developer_data'], Object);
      if (data.hasOwnProperty('public_interest_stats'))
        obj.publicInterestStats = ApiClient.convertToType(data['public_interest_stats'], Object);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Object} localization
   */
  exports.prototype.localization = undefined;

  /**
   * @member {Object} image
   */
  exports.prototype.image = undefined;

  /**
   * @member {Object} marketData
   */
  exports.prototype.marketData = undefined;

  /**
   * @member {Object} communityData
   */
  exports.prototype.communityData = undefined;

  /**
   * @member {Object} developerData
   */
  exports.prototype.developerData = undefined;

  /**
   * @member {Object} publicInterestStats
   */
  exports.prototype.publicInterestStats = undefined;


  return exports;

}));
