/*
 * recreationms_trading_tool
 * a simple trading tool to return the percentage drop of a coin using coingecko api for rates and historical data
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Data'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Data'));
  } else {
    // Browser globals (root is window)
    if (!root.RecreationmsTradingTool) {
      root.RecreationmsTradingTool = {};
    }
    root.RecreationmsTradingTool.CurrentPriceApi = factory(root.RecreationmsTradingTool.ApiClient, root.RecreationmsTradingTool.Data);
  }
}(this, function(ApiClient, Data) {
  'use strict';

  /**
   * CurrentPrice service.
   * @module api/CurrentPriceApi
   * @version 1.0.3
   */

  /**
   * Constructs a new CurrentPriceApi. 
   * @alias module:api/CurrentPriceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the simplePriceGet operation.
     * @callback module:api/CurrentPriceApi~simplePriceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Data} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns price data
     * it returns the price data of the specified ids compared the vs_currencies
     * @param {Object} opts Optional parameters
     * @param {String} opts.ids simple id or ids of currency, e.g. bitcoin, use comma separated strings for more than one ids
     * @param {String} opts.vsCurrencies the currency to be compared to, e.g. usd
     * @param {String} opts.includeMarketCap render true or false
     * @param {String} opts.include24hrVol render true or false
     * @param {String} opts.include24hrChange render true or false
     * @param {String} opts.includeLastUpdatedAt render true or false
     * @param {module:api/CurrentPriceApi~simplePriceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Data}
     */
    this.simplePriceGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'ids': opts['ids'],
        'vs_currencies': opts['vsCurrencies'],
        'include_market_cap': opts['includeMarketCap'],
        'include_24hr_vol': opts['include24hrVol'],
        'include_24hr_change': opts['include24hrChange'],
        'include_last_updated_at': opts['includeLastUpdatedAt'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Data;

      return this.apiClient.callApi(
        '/simple/price', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
