/*
 * recreationms_trading_tool
 * a simple trading tool to return the percentage drop of a coin using coingecko api for rates and historical data
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Data', 'model/HistoricalData', 'api/CurrentPriceApi', 'api/HistoricalPriceApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Data'), require('./model/HistoricalData'), require('./api/CurrentPriceApi'), require('./api/HistoricalPriceApi'));
  }
}(function(ApiClient, Data, HistoricalData, CurrentPriceApi, HistoricalPriceApi) {
  'use strict';

  /**
   * a_simple_trading_tool_to_return_the_percentage_drop_of_a_coin_using_coingecko_api_for_rates_and_historical_data.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var RecreationmsTradingTool = require('index'); // See note below*.
   * var xxxSvc = new RecreationmsTradingTool.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new RecreationmsTradingTool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new RecreationmsTradingTool.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new RecreationmsTradingTool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.3
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Data model constructor.
     * @property {module:model/Data}
     */
    Data: Data,
    /**
     * The HistoricalData model constructor.
     * @property {module:model/HistoricalData}
     */
    HistoricalData: HistoricalData,
    /**
     * The CurrentPriceApi service constructor.
     * @property {module:api/CurrentPriceApi}
     */
    CurrentPriceApi: CurrentPriceApi,
    /**
     * The HistoricalPriceApi service constructor.
     * @property {module:api/HistoricalPriceApi}
     */
    HistoricalPriceApi: HistoricalPriceApi
  };

  return exports;
}));
