/*
 * recreationms_trading_tool
 * a simple trading tool to return the percentage drop of a coin using coingecko api for rates and historical data
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecreationmsTradingTool);
  }
}(this, function(expect, RecreationmsTradingTool) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecreationmsTradingTool.HistoricalPriceApi();
  });

  describe('(package)', function() {
    describe('HistoricalPriceApi', function() {
      describe('coinsIdHistoryGet', function() {
        it('should call coinsIdHistoryGet successfully', function(done) {
          // TODO: uncomment, update parameter values for coinsIdHistoryGet call and complete the assertions
          /*
          var id = "id_example";
          var opts = {};
          opts._date = "_date_example";
          opts.localization = "localization_example";

          instance.coinsIdHistoryGet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(RecreationmsTradingTool.HistoricalData);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.symbol).to.be.a('string');
            expect(data.symbol).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.localization).to.be.a(Object);
            expect(data.localization).to.be();
            expect(data.image).to.be.a(Object);
            expect(data.image).to.be();
            expect(data.marketData).to.be.a(Object);
            expect(data.marketData).to.be();
            expect(data.communityData).to.be.a(Object);
            expect(data.communityData).to.be();
            expect(data.developerData).to.be.a(Object);
            expect(data.developerData).to.be();
            expect(data.publicInterestStats).to.be.a(Object);
            expect(data.publicInterestStats).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
